USE [AYIZA_DB]
GO

/****** Object:  Table [dbo].[UserTitle]    Script Date: 11/6/2017 12:22:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AY_Title](
	[AY_F_TitleId] [int] IDENTITY(1,1) NOT NULL,
	[AY_F_Description] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[AY_F_TitleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


